spring:
  data:
    mongodb:
      host: mongo-dev
      port: 27017
      database: ordermanager
      username: om
      password: om1234
      auto-index-creation: true

logging:
  level:
    org.springframework.data: debug
    com.danielbican: debug
